### ISSUE TITLE
do anyone know how to use fileRun with Thunderbird.

### ISSUE THREAD

**Issue by luxter111** [filerun/api-client#2]
hi,
do any person know how to use FileRun with Thunderbird, FileRun installation URL, clientID(not a username), Client Secret(not your password).
how can these be obtained?
thanks.

**Comment by filerun** [comment]
Checking the FileRun documentation would help: http://docs.filerun.com/thunderbird_filelink_addon

**Comment by luxter111** [comment]
It's so boring only animals can understand this document.

Sent from Yahoo Mail on Android<https://go.onelink.me/107872968?pid=InProduct&c=Global_Internal_YGrowth_AndroidEmailSig__AndroidUsers&af_wl=ym&af_sub1=Internal&af_sub2=Global_YGrowth&af_sub3=EmailSignature>

On Wed, May 22, 2019 at 1:42 AM, FileRun
<notifications@github.com> wrote:

Checking the FileRun documentation would help: http://docs.filerun.com/thunderbird_filelink_addon
